version: "3.1"

services:
  postgres-first:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data-first:/var/lib/postgresql/data:Z

  postgres-third:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data-third:/var/lib/postgresql/data:Z
    ports:
      - 45432:5432

  first-service-rest:
    build: first-service-rest
    depends_on:
      - first-service-soap
    ports:
      - 47893:8443

  first-service-mule:
    build: mule
    depends_on:
      - first-service-soap
    ports:
      - 8083:8081

  first-service-soap:
    build: first-service-soap/
    depends_on:
      - postgres-first
    ports:
      - 8085:8085

  second-service-config-server:
    build: second-service-config-server/

  second-service-eureka-server:
    build: second-service-eureka-server/
    ports:
      - 8761:8761

  second-service-zuul:
    build: second-service-zuul/
    depends_on:
      - second-service-eureka-server
      - second-service-rest

  second-service-rest:
    build: second-service-rest/
    depends_on:
      - second-service-config-server
      - first-service-soap
    command: sh -c '/usr/bin/wait-for second-service-config-server:8080 -- java -jar /second-service-rest.war'
    ports:
      - 8263:8443
    deploy:
      replicas: 1

  third-service:
    build: third-service-vertx/
    depends_on:
      - postgres-third
    ports:
      - 8889:8080

  frontend:
    build: frontend/
    ports:
      - 443:443
    depends_on:
      - first-service-soap
      - second-service-zuul
      - third-service
volumes:
  #because Docker on Windows has bug and Windows folder can not be used by postgres container
  pg-data-first:
    external: true
  pg-data-third:
    external: true