version: "3.1"

services:
  postgres-first:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data-first:/var/lib/postgresql/data:Z

  postgres-third:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data-third:/var/lib/postgresql/data:Z
    ports:
      - 45432:5432

  first-service-consul:
    image: consul
    command: agent -server -ui -node=server1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - 8500:8500

  first-service-ejb:
    build: first-service-ejb/
    depends_on:
      - postgres-first
      - first-service-consul

  first-service-rest:
    build: first-service-rest/
    ports:
      - 8080:8443
    depends_on:
      - first-service-ejb
      - first-service-consul

  second-service-config-server:
    build: second-service-config-server/
    ports:
      - 48080:8080

  second-service-eureka-server:
    build: second-service-eureka-server/
    ports:
      - 8761:8761

  second-service-zuul:
    build: second-service-zuul/
    ports:
      - 48081:8443
    depends_on:
      - second-service-eureka-server

  second-service-rest:
    build: second-service-rest/
    depends_on:
      - second-service-config-server
    command: sh -c '/usr/bin/wait-for second-service-config-server:8080 -- java -jar /second-service-rest.war'
    deploy:
      replicas: 2

  third-service:
    build: third-service/
    depends_on:
      - postgres-third

  frontend:
    build: frontend/
    ports:
      - 3000:80
      - 443:443
    depends_on:
      - first-service-rest
      - second-service-rest
volumes:
  #because Docker on Windows has bug and Windows folder can not be used by postgres container
  pg-data-first:
    external: true
  pg-data-third:
    external: true