version: "3.1"

services:
  postgres-first:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data-first:/var/lib/postgresql/data:Z

  postgres-third:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data-third:/var/lib/postgresql/data:Z
    ports:
      - 45432:5432

  first-service-soap:
    build: first-service-soap/
    depends_on:
      - postgres-first
    ports:
      - 8090:8090
      - 9990:9990
      - 8080:8080

  second-service-config-server:
    build: second-service-config-server/

  second-service-eureka-server:
    build: second-service-eureka-server/
    ports:
      - 8761:8761

  second-service-zuul:
    build: second-service-zuul/
    depends_on:
      - second-service-eureka-server

  second-service-rest:
    build: second-service-rest/
    depends_on:
      - second-service-config-server
    command: sh -c '/usr/bin/wait-for second-service-config-server:8080 -- java -jar /second-service-rest.war'
    deploy:
      replicas: 2

  third-service:
    build: third-service/
    depends_on:
      - postgres-third

  frontend:
    build: frontend/
    ports:
      - 443:443
    depends_on:
      - first-service-soap
      - second-service-rest
volumes:
  #because Docker on Windows has bug and Windows folder can not be used by postgres container
  pg-data-first:
    external: true
  pg-data-third:
    external: true