custom:
  rest-client:
    catalog:
      trust-store: /ssl/firstservice.jks
      trust-store-password: password

server:
  servlet:
    context-path: /second-service-rest
  ssl:
    key-store: /ssl/secondservice.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: secondservice
    key-password: password
    enabled: true
  port: 8443
spring:
  application:
    name: second
  profiles:
    active: prod
  config:
    import: "configserver:http://second-service-config-server:8080"