quarkus:
  http:
    cors: true
    root-path: /third-service
    ssl-port: 8443
    ssl:
      certificate:
        key-store-file: /ssl/quarkuskeystore
        key-store-password: changeit
    insecure-requests: disabled
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://postgres-third:5432/postgres
  hibernate-orm:
    database:
      generation: update