quarkus:
  http:
    cors: true
    root-path: /third-service
    ssl-port: 49728
    ssl:
      certificate:
        key-store-file: ./quarkuskeystore
        key-store-password: changeit
    insecure-requests: disabled
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/postgres